### ISSUE TITLE
[BUG] Error installing lenovolegionlinux-dkms-git on cachyos. Module legion_laptop is not currently loaded

### ISSUE THREAD

**Issue by S-North** [johnfanv2/LenovoLegionLinux#358]
**Problem Description**
When installing via cachyos package manager or  paru I get following errors;
```text
(2/2) installing lenovolegionlinux-dkms-git                                                                                   [----------------------------------------------------------------------------] 100%
rmmod: ERROR: Module legion_laptop is not currently loaded
Installation Finished!
```
AND
```text
(2/6) Install DKMS modules
==> dkms install --no-depmod lenovolegionlinux/1.0.0 -k 6.12.50-2-cachyos-lts
==> dkms install --no-depmod lenovolegionlinux/1.0.0 -k 6.17.1-2-cachyos

Error! Bad return status for module build on kernel: 6.17.1-2-cachyos (x86_64)
Consult /var/lib/dkms/lenovolegionlinux/1.0.0/build/make.log for more information.
==> WARNING: `dkms install --no-depmod lenovolegionlinux/1.0.0 -k 6.17.1-2-cachyos' exited 10
==> depmod 6.12.50-2-cachyos-lts
```

When I run legion_gui --use_legion_cli_to_write I get
```text
Traceback (most recent call last):
  File "/usr/bin/legion_gui", line 5, in <module>
    from legion_linux.legion_gui import main
ModuleNotFoundError: No module named 'legion_linux'
```

I found what looked like a similar issue at #214 and tried 
```text
sudo dkms install --no-depmod lenovolegionlinux/1.0.0 -k 6.17.1-2-cachyos

Sign command: /usr/lib/modules/6.17.1-2-cachyos/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub

Building module(s)...(bad exit status: 2)
Failed command:
make -j12 KERNELRELEASE=6.17.1-2-cachyos KERNELVERSION=6.17.1-2-cachyos LLVM=1

Error! Bad return status for module build on kernel: 6.17.1-2-cachyos (x86_64)
Consult /var/lib/dkms/lenovolegionlinux/1.0.0/build/make.log for more information.
```

And the contents of /var/lib/dkms/lenovolegionlinux/1.0.0/build/make.log is;
```text
DKMS (dkms-3.2.2) make.log for lenovolegionlinux/1.0.0 for kernel 6.17.1-2-cachyos (x86_64)
Thu  9 Oct 17:33:49 BST 2025

Building module(s)
# command: make -j12 KERNELRELEASE=6.17.1-2-cachyos KERNELVERSION=6.17.1-2-cachyos LLVM=1
make -C /lib/modules/6.17.1-2-cachyos/build M=/var/lib/dkms/lenovolegionlinux/1.0.0/build modules
make[1]: Entering directory '/usr/lib/modules/6.17.1-2-cachyos/build'
make[2]: Entering directory '/var/lib/dkms/lenovolegionlinux/1.0.0/build'
  CC [M]  legion-laptop.o
legion-laptop.c:2321:34: error: field has incomplete type 'struct platform_profile_handler'
 
 2321 |         struct platform_profile_handler platform_profile_handler;
      |                                         ^
legion-laptop.c:2321:9: note: forward declaration of 'struct platform_profile_handler'
 2321 |         struct platform_profile_handler platform_profile_handler;
      |                ^
legion-laptop.c:4781:26: error: too few arguments to function call, single argument 'dev' was not specified
 4781 |         platform_profile_notify();
      |         ~~~~~~~~~~~~~~~~~~~~~~~ ^
/usr/lib/modules/6.17.1-2-cachyos/build/include/linux/platform_profile.h:58:6: note: 'platform_profile_notify' declared here
   58 | void platform_profile_notify(struct device *dev);
      |      ^                       ~~~~~~~~~~~~~~~~~~
legion-laptop.c:4881:26: error: too few arguments to function call, single argument 'dev' was not specified
 4881 |         platform_profile_remove();
      |         ~~~~~~~~~~~~~~~~~~~~~~~ ^
/usr/lib/modules/6.17.1-2-cachyos/build/include/linux/platform_profile.h:53:6: note: 'platform_profile_remove' declared here
   53 | void platform_profile_remove(struct device *dev);
      |      ^                       ~~~~~~~~~~~~~~~~~~
legion-laptop.c:6146:3: error: field designator 'remove_new' does not refer to any field in type 'struct platform_driver'
 6146 |         .remove_new = legion_remove,
      |         ~^~~~~~~~~~~~~~~~~~~~~~~~~~
4 errors generated.
make[4]: *** [/usr/lib/modules/6.17.1-2-cachyos/build/scripts/Makefile.build:287: legion-laptop.o] Error 1
make[3]: *** [/usr/lib/modules/6.17.1-2-cachyos/build/Makefile:2016: .] Error 2
make[2]: *** [/usr/lib/modules/6.17.1-2-cachyos/build/Makefile:248: __sub-make] Error 2
make[2]: Leaving directory '/var/lib/dkms/lenovolegionlinux/1.0.0/build'
make[1]: *** [Makefile:248: __sub-make] Error 2
make[1]: Leaving directory '/usr/lib/modules/6.17.1-2-cachyos/build'
make: *** [Makefile:13: all] Error 2

# exit code: 2
# elapsed time: 00:00:01
----------------------------------------------------------------
```

I checked that /var/lib/dkms/lenovolegionlinux/ was successfully removed before reinstalling.
The final comment on that issue before it was closed was a suggested kernel patch for 6.13. I have not tried this as it is for an old kernel version and I am not at all knowledgeable in kernel patching.

**Model and Debug Info**

Installation type: cachyos package manager & via paru
Distribution: 6.17.1-2-cachyos
Model name: Lenovo legion 5 15ARH05
CPU model: AMD Ryzen 5 4600H
GPU model: NVIDIA GeForce GTX 1650
Keyboard backlight: single color with off/medium/bright)
Light in lid or logo: no
Light at IO-Ports at back: power led only

Output of `sudo dmidecode -t system`. Please remove Serial Number and UUID for privacy:
```text
# dmidecode 3.6
Getting SMBIOS data from sysfs.
SMBIOS 3.2.0 present.

Handle 0x0001, DMI type 1, 27 bytes
System Information
	Manufacturer: LENOVO
	Product Name: 82B5
	Version: Lenovo Legion 5-15ARH05
	Serial Number: PF24057V
	UUID: c536d07e-2992-1c5b-b1c7-b80835999ad7
	Wake-up Type: Power Switch
	SKU Number: LENOVO_MT_82B5_BU_idea_FM_Legion 5-15ARH05
	Family: Legion 5-15ARH05

Handle 0x0020, DMI type 12, 5 bytes
System Configuration Options
	Option 1: String1 for Type12 Equipment Manufacturer
	Option 2: String2 for Type12 Equipment Manufacturer
	Option 3: String3 for Type12 Equipment Manufacturer
	Option 4: String4 for Type12 Equipment Manufacturer

Handle 0x0030, DMI type 32, 20 bytes
System Boot Information
	Status: No errors detected
```

Output of `sudo dmidecode -t bios`:
```text
# dmidecode 3.6
Getting SMBIOS data from sysfs.
SMBIOS 3.2.0 present.

Handle 0x0000, DMI type 0, 26 bytes
BIOS Information
	Vendor: LENOVO
	Version: EUCN39WW
	Release Date: 09/09/2022
	Address: 0xE0000
	Runtime Size: 128 kB
	ROM Size: 15488 kB
	Characteristics:
		PCI is supported
		BIOS is upgradeable
		BIOS shadowing is allowed
		Boot from CD is supported
		Selectable boot is supported
		EDD is supported
		Japanese floppy for NEC 9800 1.2 MB is supported (int 13h)
		Japanese floppy for Toshiba 1.2 MB is supported (int 13h)
		5.25"/360 kB floppy services are supported (int 13h)
		5.25"/1.2 MB floppy services are supported (int 13h)
		3.5"/720 kB floppy services are supported (int 13h)
		3.5"/2.88 MB floppy services are supported (int 13h)
		8042 keyboard services are supported (int 9h)
		CGA/mono video services are supported (int 10h)
		ACPI is supported
		USB legacy is supported
		BIOS boot specification is supported
		Targeted content distribution is supported
		UEFI is supported
	BIOS Revision: 1.39
	Firmware Revision: 1.39

Handle 0x0021, DMI type 13, 22 bytes
BIOS Language Information
	Language Description Format: Long
	Installable Languages: 4
		en|US|iso8859-1
		fr|FR|iso8859-1
		ja|JP|unicode
		zh|TW|unicode
	Currently Installed Language: en|US|iso8859-1
```

Output of `sudo cat /sys/kernel/debug/legion/fancurve`:
```text
cat: /sys/kernel/debug/legion/fancurve: No such file or directory)
```

**Comment by MrFrankfromM** [comment]
same on my installation

**Comment by oishikm12** [comment]
In case anyone is still facing this issue, I was able to fix this by not using the packages in cachyos repo (my system is 16ACH6H),

Instead I cloned the package from Git directly, 

- Install all the dependencies, `linux-headers base-devel lm_sensors git dmidecode python-pyqt6 python-yaml python-argcomplete python-darkdetect`
  - For installing GUI, some other packages like `python-setuptools`, `python-build` & `python-installer` might  be required
- Navigate to `cd LenovoLegionLinux/kernel_module/`
- Runt the commands, 
   ```
    sudo make LLVM=1
    sudo make reloadmodule  LLVM=1
    sudo make install  LLVM=1
   ```
- By this point the commands for checking fan curve and kernel logs showed expected output (PlasmaVantage widget for KDE worked as well) - https://github.com/johnfanv2/LenovoLegionLinux#octocat-initial-usage-testing
  - You can follow instructions for DKMS as well - https://github.com/johnfanv2/LenovoLegionLinux#installing-via-dkms
  - For legiond - https://github.com/johnfanv2/LenovoLegionLinux#lenovo-legion-laptop-support-daemonlegiond

For the GUI, 

- Navigate to `cd LenovoLegionLinux/python/legion_linux/`
- Build the package - `python -m build --wheel --no-isolation`
- Install it - `sudo python -m installer --destdir="/" dist/*.whl`
