### PR TITLE
fix(build): build with the LLVM toolchain automatically on clang-built kernels

### LINKED ISSUE #358: [BUG] Error installing lenovolegionlinux-dkms-git on cachyos. Module legion_laptop is not currently loaded
**Problem Description**
When installing via cachyos package manager or  paru I get following errors;
```text
(2/2) installing lenovolegionlinux-dkms-git                                                                                   [----------------------------------------------------------------------------] 100%
rmmod: ERROR: Module legion_laptop is not currently loaded
Installation Finished!
```
AND
```text
(2/6) Install DKMS modules
==> dkms install --no-depmod lenovolegionlinux/1.0.0 -k 6.12.50-2-cachyos-lts
==> dkms install --no-depmod lenovolegionlinux/1.0.0 -k 6.17.1-2-cachyos

Error! Bad return status for module build on kernel: 6.17.1-2-cachyos (x86_64)
Consult /var/lib/dkms/lenovolegionlinux/1.0.0/build/make.log for more information.
==> WARNING: `dkms install --no-depmod lenovolegionlinux/1.0.0 -k 6.17.1-2-cachyos' exited 10
==> depmod 6.12.50-2-cachyos-lts
```

When I run legion_gui --use_legion_cli_to_write I get
```text
Traceback (most recent call last):
  File "/usr/bin/legion_gui", line 5, in <module>
    from legion_linux.legion_gui import main
ModuleNotFoundError: No module named 'legion_linux'
```

I found what looked like a similar issue at #214 and tried 
```text
sudo dkms install --no-depmod lenovolegionlinux/1.0.0 -k 6.17.1-2-cachyos

Sign command: /usr/lib/modules/6.17.1-2-cachyos/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub

Building module(s)...(bad exit status: 2)
Failed command:
make -j12 KERNELRELEASE=6.17.1-2-cachyos KERNELVERSION=6.17.1-2-cachyos LLVM=1

Error! Bad return status for module build on kernel: 6.17.1-2-cachyos (x86_64)
Consult /var/lib/dkms/lenovolegionlinux/1.0.0/build/make.log for more information.
```

And the contents of /var/lib/dkms/lenovolegionlinux/1.0.0/build/make.log is;
```text
DKMS (dkms-3.2.2) make.log for lenovolegionlinux/1.0.0 for kernel 6.17.1-2-cachyos (x86_64)
Thu  9 Oct 17:33:49 BST 2025

Building module(s)
# command: make -j12 KERNELRELEASE=6.17.1-2-cachyos KERNELVERSION=6.17.1-2-cachyos LLVM=1
make -C /lib/modules/6.17.1-2-cachyos/build M=/var/lib/dkms/lenovolegionlinux/1.0.0/build modules
make[1]: Entering directory '/usr/lib/modules/6.17.1-2-cachyos/build'
make[2]: Entering directory '/var/lib/dkms/lenovolegionlinux/1.0.0/build'
  CC [M]  legion-laptop.o
legion-laptop.c:2321:34: error: field has incomplete type 'struct platform_profile_handler'
 
 2321 |         struct platform_profile_handler platform_profile_handler;
      |                                         ^
legion-laptop.c:2321:9: note: forward declaration of 'struct platform_profile_handler'
 2321 |         struct platform_profile_handler platform_profile_handler;
      |                ^
legion-laptop.c:4781:26: error: too few arguments to function call, single argument 'dev' was not specified
 4781 |         platform_profile_notify();
      |         ~~~~~~~~~~~~~~~~~~~~~~~ ^
/usr/lib/modules/6.17.1-2-cachyos/build/include/linux/platform_profile.h:58:6: note: 'platform_profile_notify' declared here
   58 | void platform_profile_notify(struct device *dev);
      |      ^                       ~~~~~~~~~~~~~~~~~~
legion-laptop.c:4881:26: error: too few arguments to function call, single argument 'dev' was not specified
 4881 |         platform_profile_remove();
      |         ~~~~~~~~~~~~~~~~~~~~~~~ ^
/usr/lib/modules/6.17.1-2-cachyos/build/include/linux/platform_profile.h:53:6: note: 'platform_profile_remove' declared here
   53 | void platform_profile_remove(struct device *dev);
      |      ^                       ~~~~~~~~~~~~~~~~~~
legion-laptop.c:6146:3: error: field designator 'remove_new' does not refer to any field in type 'struct platform_driver'
 6146 |         .remove_new = legion_remove,
      |         ~^~~~~~~~~~~~~~~~~~~~~~~~~~
4 errors generated.
make[4]: *** [/usr/lib/modules/6.17.1-2-cachyos/build/scripts/Makefile.build:287: legion-laptop.o] Error 1
make[3]: *** [/usr/lib/modules/6.17.1-2-cachyos/build/Makefile:2016: .] Error 2
make[2]: *** [/usr/lib/modules/6.17.1-2-cachyos/build/Makefile:248: __sub-make] Error 2
make[2]: Leaving directory '/var/lib/dkms/lenovolegionlinux/1.0.0/build'
make[1]: *** [Makefile:248: __sub-make] Error 2
make[1]: Leaving directory '/usr/lib/modules/6.17.1-2-cachyos/build'
make: *** [Makefile:13: all] Error 2

# exit code: 2
# elapsed time: 00:00:01
----------------------------------------------------------------
```

I checked that /var/lib/dkms/lenovolegionlinux/ was successfully removed before reinstalling.
The final comment on that issue before it was closed was a suggested kernel patch for 6.13. I have not tried this as it is for an old kernel version and I am not at all knowledgeable in kernel patching.

**Model and Debug Info**

Installation type: cachyos package manager & via paru
Distribution: 6.17.1-2-cachyos
Model name: Lenovo legion 5 15ARH05
CPU model: AMD Ryzen 5 4600H
GPU model: NVIDIA GeForce GTX 1650
Keyboard backlight: single color with off/medium/bright)
Light in lid or logo: no
Light at IO-Ports at back: power led only

Output of `sudo dmidecode -t system`. Please remove Serial Number and UUID for privacy:
```text
# dmidecode 3.6
Getting SMBIOS data from sysfs.
SMBIOS 3.2.0 present.

Handle 0x0001, DMI type 1, 27 bytes
System Information
	Manufacturer: LENOVO
	Product Name: 82B5
	Version: Lenovo Legion 5-15ARH05
	Serial Number: PF24057V
	UUID: c536d07e-2992-1c5b-b1c7-b80835999ad7
	Wake-up Type: Power Switch
	SKU Number: LENOVO_MT_82B5_BU_idea_FM_Legion 5-15ARH05
	Family: Legion 5-15ARH05

Handle 0x0020, DMI type 12, 5 bytes
System Configuration Options
	Option 1: String1 for Type12 Equipment Manufacturer
	Option 2: String2 for Type12 Equipment Manufacturer
	Option 3: String3 for Type12 Equipment Manufacturer
	Option 4: String4 for Type12 Equipment Manufacturer

Handle 0x0030, DMI type 32, 20 bytes
System Boot Information
	Status: No errors detected
```

Output of `sudo dmidecode -t bios`:
```text
# dmidecode 3.6
Getting SMBIOS data from sysfs.
SMBIOS 3.2.0 present.

Handle 0x0000, DMI type 0, 26 bytes
BIOS Information
	Vendor: LENOVO
	Version: EUCN39WW
	Release Date: 09/09/2022
	Address: 0xE0000
	Runtime Size: 128 kB
	ROM Size: 15488 kB
	Characteristics:
		PCI is supported
		BIOS is upgradeable
		BIOS shadowing is allowed
		Boot from CD is supported
		Selectable boot is supported
		EDD is supported
		Japanese floppy for NEC 9800 1.2 MB is supported (int 13h)
		Japanese floppy for Toshiba 1.2 MB is supported (int 13h)
		5.25"/360 kB floppy services are supported (int 13h)
		5.25"/1.2 MB floppy services are supported (int 13h)
		3.5"/720 kB floppy services are supported (int 13h)
		3.5"/2.88 MB floppy services are supported (int 13h)
		8042 keyboard services are supported (int 9h)
		CGA/mono video services are supported (int 10h)
		ACPI is supported
		USB legacy is supported
		BIOS boot specification is supported
		Targeted content distribution is supported
		UEFI is supported
	BIOS Revision: 1.39
	Firmware Revision: 1.39

Handle 0x0021, DMI type 13, 22 bytes
BIOS Language Information
	Language Description Format: Long
	Installable Languages: 4
		en|US|iso8859-1
		fr|FR|iso8859-1
		ja|JP|unicode
		zh|TW|unicode
	Currently Installed Language: en|US|iso8859-1
```

Output of `sudo cat /sys/kernel/debug/legion/fancurve`:
```text
cat: /sys/kernel/debug/legion/fancurve: No such file or directory)
```

### PR DESCRIPTION
**Pull request by Hishammm0**
Model: **Lenovo Legion Pro 5 16IRX8 (82WK), BIOS KWCN54WW**, on CachyOS 7.2.4-3-cachyos. The fix is not
model-specific; it applies to any kernel built with clang.

Fixes #358. Part of #564.

Out-of-tree builds against a kernel compiled with clang (`CONFIG_CC_IS_CLANG=y`, e.g. CachyOS) fail with gcc,
because the kernel's own flags are clang-only:

```text
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: clang version 22.1.8
  You are using:           gcc (GCC) 16.2.1
gcc: error: unrecognized command-line option '-mstack-alignment=8'
gcc: error: unrecognized command-line option '-mretpoline-external-thunk'
gcc: error: unrecognized command-line option '-mllvm'
```

Detect `CONFIG_CC_IS_CLANG` in the target kernel's configuration and pass `LLVM=1` to the kernel build unless
`LLVM` is given on the command line, so that plain `make`, `make install` and the DKMS build all work without a
manual flag. dkms 3.x does the same detection for the build command it runs itself, but `dkms.conf` here invokes
this Makefile, so the Makefile has to know too.

Three smaller fixes come with it, all in the same area:

- `LLVM` is always passed to the sub-make explicitly, with an empty value when it is 0. Without that, make carries
  the detected `LLVM=1` into the sub-make through `MAKEOVERRIDES` and a command-line `LLVM=0` has no effect.
- The detection reads `include/config/auto.conf` as well as `.config`, with `grep -qs` so a missing file is quiet.
- `dkms.conf` passes `KSRC=${kernel_source_dir}`, so `dkms --kernelsourcedir` and the detection cannot disagree,
  and `make install` / `make uninstall` run `depmod -a $(KERNELVERSION)` instead of the undefined `$(KVER)`, which
  had them updating the running kernel's module index when building for a different kernel.

## Verification

On CachyOS 7.2.4-3-cachyos (clang 22.1.8):

```text
$ make                     # was: gcc errors as above
make -C /lib/modules/7.2.4-3-cachyos/build M=.../kernel_module LLVM=1 modules
  CC [M]  legion-laptop.o
  LD [M]  legion-laptop.ko
$ make LLVM=0              # override honoured: gcc is selected again
  The kernel was built by: clang version 22.1.8
  You are using:           gcc
```

`sudo make install` then `modprobe legion_laptop` loads the module, and it has been running as the permanent
install on this machine since. On a gcc-built kernel nothing changes: the detection does not fire and the sub-make
is invoked exactly as before.

`tests/test_kernel_checkpath.sh` is unaffected and still clean.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by armoox** [comment]
Reviewing against the current `kernel_module/Makefile` and `dkms.conf`.

### This one is ready

Checked the mechanics against the current build flow:

- LLVM detection via `CONFIG_CC_IS_CLANG=y` in `include/config/auto.conf` is reliable (missing auto.conf ⇒ grep fails ⇒ no `LLVM` forced; empty `LLVM=` is passed so a set-but-empty variable overrides an exported `LLVM` through `MAKEOVERRIDES`, which is exactly the documented trick).
- `depmod -a $(KERNELVERSION)` is a genuine fix: the old `$(KVER)` was never defined, so it silently ran `depmod -a` on the running kernel even when targeting another one. Now it follows `KERNELVERSION` consistently.
- `MAKE[0]="make KERNELVERSION=${kernelver} KSRC=${kernel_source_dir}"` in `dkms.conf` gives the Makefile a resolvable `KSRC` for the auto.conf check under DKMS.
- The `wmi_write_fancurve_custom` loop refactor referenced by the PR description is byte-equivalent (0x06..0x18 = 0x06 + 2*point).

Two tiny nits, neither blocking:

1. `moduleInContainer` and `allWarn` still use the old `-C $(KSRC) M=$(shell pwd)` form; `allWarn` in particular would not benefit from the LLVM detection (minor inconsistency, not a bug).
2. Consider also honoring an explicit `LLVM=1` on the command line for systems that *don't* grep as clang but are forced — already handled by `LLVM ?= 1` not clipping user overrides (verified: `filter-out 0` + `LLVM=` empty case). Good.

**Verdict:** safe to merge. The Makefile behavior is unchanged for gcc-built kernels and correctly self-configures on clang-built ones.
